In [4]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [5]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset = pd.read_csv('/content/gdrive/MyDrive/archive/fuzzyc_means.csv')

In [7]:
X = dataset.iloc[:, 0:9].values

In [8]:
y = dataset.iloc[:, -1].values

In [9]:
print(X)
print(y)

[[8.98510e-02 8.38710e-01 3.69770e-01 ... 7.55560e-01 1.80000e-04
  1.04200e-02]
 [6.63157e-01 8.81720e-01 3.02300e-02 ... 6.66670e-01 5.70000e-04
  9.89580e-01]
 [1.80040e-02 9.78490e-01 2.76740e-01 ... 7.11110e-01 5.44000e-03
  9.16670e-01]
 ...
 [1.14950e-02 7.84950e-01 4.65100e-02 ... 7.11110e-01 8.40000e-04
  6.14580e-01]
 [1.40830e-02 8.49460e-01 2.79100e-02 ... 8.22220e-01 2.40000e-04
  9.89580e-01]
 [5.64340e-02 6.98920e-01 3.67440e-01 ... 8.22220e-01 1.27000e-03
  7.29200e-02]]
[0 2 2 ... 2 2 0]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
import keras

In [13]:
from keras.models import Sequential

In [14]:
from keras.layers import Dense

In [15]:
classifier = Sequential()

In [ ]:
#classifier.add(Dense(units = 9,  activation = 'relu', input_dim = 9))

In [ ]:
#classifier.add(Dense(units = 27, activation = 'relu'))

In [ ]:
#classifier.add(Dense(units=1, activation = 'sigmoid'))

In [ ]:
#lassifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
# classifier.fit(X_train, y_train, batch_size = 9, nb_epoch = 100)

In [16]:


classifier.add(Dense(9, kernel_initializer = 'uniform', activation = 'relu', input_dim = 9))
classifier.add(Dense(36,kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid')) 

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', 
                metrics = ['accuracy']) 

#classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

classifier.fit(X_train, y_train, batch_size = 9, epochs = 100)

Epoch 1/100
223/223 [==============================] - 1s 2ms/step - loss: -2.5975 - accuracy: 0.1936
Epoch 2/100
223/223 [==============================] - 0s 2ms/step - loss: -66.6411 - accuracy: 0.2450
Epoch 3/100
223/223 [==============================] - 0s 2ms/step - loss: -333.1426 - accuracy: 0.2690
Epoch 4/100
223/223 [==============================] - 0s 2ms/step - loss: -926.6957 - accuracy: 0.2750
Epoch 5/100
223/223 [==============================] - 0s 2ms/step - loss: -1933.1683 - accuracy: 0.2750
Epoch 6/100
223/223 [==============================] - 1s 3ms/step - loss: -3455.3721 - accuracy: 0.2725
Epoch 7/100
223/223 [==============================] - 1s 4ms/step - loss: -5525.9429 - accuracy: 0.2710
Epoch 8/100
223/223 [==============================] - 1s 4ms/step - loss: -8199.3320 - accuracy: 0.2725
Epoch 9/100
223/223 [==============================] - 1s 5ms/step - loss: -11546.5283 - accuracy: 0.2690
Epoch 10/100
223/223 [==============================] - 1s 5m

In [19]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred)

In [20]:
print(y_pred)

[[1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 68  73   0   0]
 [ 58  43   0   0]
 [  7 107   0   0]
 [  0 146   0   0]]


In [24]:
#Predicting result for Single Observation
print(classifier.predict(([[5.3224,	1.5469,	8.2467,	2.0020	,2.9087	,0.4234,	4.4561,	7.00544,	3.1234	]])) > 0.5)

[[False]]


In [27]:
#accuracy core on training data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(y_test,X_test_prediction)

In [28]:
print('Accuracy score of testing data : ', test_data_accuracy)

Accuracy score of testing data :  0.22111553784860558


In [ ]:
print('Accuracy score of training data : ', training_data_accuracy)

Accuracy score of training data :  0.19211576846307385


In [ ]:
from sklearn.metrics import accuracy_score
#accuracy core on training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(y_train,X_train_prediction)
